### ISSUE TITLE
Intégration de Bootstrap

### ISSUE THREAD

**Issue by MacBootglass** [MacBootglass/myOwnPortfolio#4]
L'importation d u JS de bootstrap4 au sein du projet n'est clairement pas optimale (copie des dépendances depuis node_modules par gulp dans répertoire du dist puis intégration dans index.html). 
Les tentatives d'intégration avec webpack n'ont pas été concluante -> Trouver une autre solution ?

**Comment by fbab** [comment]
Vu en Copro ce jour : abandon du JS de BootStrap (seul les classes CSS utiles sont importées par SCCS) . Reste à supprimer la balise script référençant bootstrap.js

**Comment by fbab** [comment]
clos.
Révision du fichier gulpfile pour éviter la copie des fichiers js dans express.
